### ISSUE TITLE
Replace `elm` variable by `localRuntime` in native code?

### ISSUE THREAD

**Issue by jvoigtlaender** [jwmerrill/elm-animation-frame#2]
Was looking at `frameWhen` to compare with `fpsWhen`. Noticed that `elm` is used for what is now consistently called `localRuntime` throughout all native code of the core lib. See https://github.com/elm-lang/core/pull/127.

**Comment by jwmerrill** [comment]
Thanks. I think that several updates will be needed to bring `frameWhen` in line with the new-and-improved behavior of `fpsWhen`.
