### ISSUE TITLE
Support for Elm 0.17

### ISSUE THREAD

**Issue by sbaechler** [jwmerrill/elm-animation-frame#7]
Version 0.17 dropped Signals in favor of Subscriptions.
http://elm-lang.org/blog/farewell-to-frp

**Comment by jwmerrill** [comment]
As of Elm 0.17, I think https://github.com/elm-lang/animation-frame will be
the way to subscribe to animation frames.

I've been waiting for some docs to point to so that I can deprecate this
library.

**Comment by jwmerrill** [comment]
Docs for your reference:
http://package.elm-lang.org/packages/elm-lang/animation-frame/1.0.0/AnimationFrame

**Comment by sbaechler** [comment]
Very well. I did not see that. Thank you.
